Iter2
ocadotechnology-university/product-eye pull request #7
Opened 2024-04-26 09:46 UTC by Quarol

2024-04-29 12:38 UTC, mekiert-ocado requested changes

2024-04-29 12:38 UTC, mekiert-ocado commented on src/Calibration.tsx
> +    const MAX_CLICKS = 12;
[optional] The constants could be outside the component.

2024-04-29 12:38 UTC, mekiert-ocado commented on src/Calibration.tsx
> +            newClickCount[index]++;
The opration is modyfing the array. You might use a map here to store clicks.

```
const newClickCount = {...clickCount, [index]: clickCount[index]++}
```

2024-04-29 12:38 UTC, mekiert-ocado commented on src/RotateObject3D.tsx
> +        //const mouseX = (event.clientX / window.innerWidth) * mouseXScaleFactor + mouseXOset;
Please remove useless comment. If it is code that will be used in the future, then describe it appropriately.

2024-05-29 07:09 UTC, mekiert-ocado commented on src/Calibration.tsx
> +            newClickCount[index]++;
@Quarol It is still not resolved.

2024-05-29 07:10 UTC, mekiert-ocado commented on src/Calibration.tsx
> +    const MAX_CLICKS = 12;
@Quarol It is still not resolved.

2024-05-29 07:10 UTC, mekiert-ocado commented on src/RotateObject3D.tsx
> +        //const mouseX = (event.clientX / window.innerWidth) * mouseXScaleFactor + mouseXOset;
@Quarol  It is still not resolved.

2024-05-30 18:30 UTC, closed without merging

2024-05-30 18:30 UTC, Quarol commented
Latest changes were not synced with pull request, I have to create a new pull request.